---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-sys-webapp-deployment
  namespace: monitoring
  labels:
    app: voting-sys-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-sys-webapp
  template:
    metadata:
      labels:
        app: voting-sys-webapp
    spec:
      serviceAccountName: voting-sys
      containers:
        - name: voting-sys-webapp
          image: gar-location-docker.pkg.dev/project-id/repository/image-name:latest
          ports:
            - name: web
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /actuator/health
              port: 5000
            periodSeconds: 10
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 512Mi