apiVersion: v1
kind: Service
metadata:
  name: voting-sys-webapp-service
  namespace: monitoring
  labels:
    app: voting-sys-webapp
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 5000
      protocol: TCP
  selector:
    app:  voting-sys-webapp